apiVersion: batch/v1
kind: Job
metadata:
  name: wdpa-convert
  labels:
    k8s-app: wdpa-convert
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 10800
  template:
    metadata:
      labels:
        k8s-app: wdpa-convert
    spec:
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - "true"
      restartPolicy: Never
      initContainers:
        - name: git-clone
          image: alpine/git:2.45.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
          command:
            - sh
            - -lc
            - |
              git clone --depth 1 "https://github.com/boettiger-lab/datasets.git" /workspace/datasets
          volumeMounts:
            - name: repo
              mountPath: /workspace
      containers:
        - name: convert-task
          image: ghcr.io/rocker-org/ml-spatial
          imagePullPolicy: Always
          workingDir: /workspace/datasets
          volumeMounts:
            - name: repo
              mountPath: /workspace
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_SECRET_ACCESS_KEY
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: nvme
                  key: MINIO_KEY
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: nvme
                  key: MINIO_SECRET
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: nvme
                  key: MINIO_ENDPOINT
            - name: AWS_S3_ENDPOINT
              value: "rook-ceph-rgw-nautiluss3.rook"
            - name: AWS_PUBLIC_ENDPOINT
              value: "s3-west.nrp-nautilus.io"
            - name: AWS_HTTPS
              value: "false"
            - name: AWS_VIRTUAL_HOSTING
              value: "FALSE"
            - name: GDAL_DATA
              value: "/opt/conda/share/gdal"
            - name: PROJ_LIB
              value: "/opt/conda/share/proj"
            - name: TMPDIR
              value: "/tmp"
          resources:
            requests:
              cpu: "4"
              memory: 64Gi
            limits:
              cpu: "4"
              memory: 64Gi
          command:
            - bash
            - -lc
            - |
              bash wdpa/convert_gdb_to_parquet.sh
      volumes:
        - name: repo
          emptyDir: {}
