[workspace]
authors = ["Carl Boettiger <cboettig@berkeley.edu>"]
channels = ["conda-forge"]
name = "datasets"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ibis-framework = ">=10.8.0,<11"
