apiVersion: batch/v1
kind: Job
metadata:
  name: sync-gbif-aws
spec:
  # Clean up the pod automatically 6000 seconds after completion
  backoffLimit: 1  # Allow a few retries
  ttlSecondsAfterFinished: 6000
  template:
    spec:
      containers:
      - name: rclone
        image: rclone/rclone:latest
        command: ["rclone", "sync", "nrp:public-gbif/2025-06", "source:us-west-2.opendata.source.coop/cboettig/gbif/2025-06"]
        # The Ceph-safe performance flags
        args:
          - "--transfers=2"       # 8 parallel file transfers (keeps Ceph happy)
          - "--checkers=4"       # 16 threads scanning for changes
          - "--tpslimit=50"       # Limit transactions/sec to prevent API throttling
          - "--progress"          # useful for logs
          - "--config=/config/rclone.conf"
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "2"
      restartPolicy: Never
      volumes:
      - name: config-volume
        secret:
          secretName: rclone-config
