apiVersion: v1
kind: ServiceAccount
metadata:
  name: cng-datasets-workflow
  namespace: biodiversity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cng-datasets-workflow
  namespace: biodiversity
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cng-datasets-workflow
  namespace: biodiversity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cng-datasets-workflow
subjects:
- kind: ServiceAccount
  name: cng-datasets-workflow
