apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: carbon-processing-cluster
spec:
  rayVersion: '2.7.0'
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        containers:
        - name: ray-head
          image: ghcr.io/rocker-org/ml-spatial:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - |
              cd /tmp
              git clone https://github.com/boettiger-lab/datasets.git
              cd datasets  
              pip install -r requirements.txt
              python -c "import ray; print('Ray imported successfully')"
              python -c "import ray; ray.start(head=True, port=6379, dashboard_host='0.0.0.0', num_cpus=2, block=True)"
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 4
              memory: 16Gi
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_S3_ENDPOINT
            value: "rook-ceph-rgw-nautiluss3.rook"
          - name: AWS_PUBLIC_ENDPOINT
            value: "s3-west.nrp-nautilus.io"
          - name: AWS_HTTPS
            value: "false"
          - name: AWS_VIRTUAL_HOSTING
            value: "FALSE"
          - name: GDAL_DATA
            value: "/opt/conda/share/gdal"
          - name: PROJ_LIB
            value: "/opt/conda/share/proj"
          command: ["/bin/bash", "-c"]
          args:
            - |
              cd /tmp &&
              git clone https://github.com/boettiger-lab/datasets.git &&
              cd datasets &&
              pip install -r requirements.txt &&
              ray start --head --port=6379 --redis-shard-ports=6380,6381 --object-manager-port=6378 --node-manager-port=6382 --dashboard-host=0.0.0.0 --num-cpus=$MY_CPU_REQUEST --block
          volumeMounts:
          - name: workspace
            mountPath: /workspace
        volumes:
        - name: workspace
          emptyDir: {}
  workerGroupSpecs:
  - replicas: 2
    minReplicas: 1
    maxReplicas: 5
    groupName: worker-group
    rayStartParams:
      num-cpus: "2"
    template:
      spec:
        containers:
        - name: ray-worker
          image: ghcr.io/rocker-org/ml-spatial:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2
              memory: 16Gi
            limits:
              cpu: 4
              memory: 32Gi
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_S3_ENDPOINT
            value: "rook-ceph-rgw-nautiluss3.rook"
          - name: AWS_PUBLIC_ENDPOINT
            value: "s3-west.nrp-nautilus.io"
          - name: AWS_HTTPS
            value: "false"
          - name: AWS_VIRTUAL_HOSTING
            value: "FALSE"
          - name: GDAL_DATA
            value: "/opt/conda/share/gdal"
          - name: PROJ_LIB
            value: "/opt/conda/share/proj"
          command: ["/bin/bash", "-c"]
          args:
          - |
            cd /tmp &&
            git clone https://github.com/boettiger-lab/datasets.git &&
            cd datasets &&
            pip install -r requirements.txt &&
            ray start --address=$RAY_HEAD_SERVICE_HOST:6379 --block
          volumeMounts:
          - name: workspace
            mountPath: /workspace
        volumes:
        - name: workspace
          emptyDir: {}
