apiVersion: batch/v1
kind: Job
metadata:
  name: wetlands-tier0
  namespace: biodiversity
  labels:
    app: wetlands
    tier: '0'
spec:
  completions: 18587
  parallelism: 100
  completionMode: Indexed
  backoffLimitPerIndex: 0
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: wetlands
        tier: '0'
    spec:
      restartPolicy: Never
      volumes:
      - name: repo
        emptyDir: {}
      containers:
      - name: worker
        image: ghcr.io/rocker-org/ml-spatial
        imagePullPolicy: Always
        workingDir: /workspace/datasets
        command:
        - bash
        - -c
        - |
          set -euo pipefail

          # Determine which index to process
          if [ -n "${INDEX_MAPPING:-}" ]; then
            # Retry tier: map completion index to failed index
            INDEX=$(python3 -c "import json, os; print(json.loads(os.environ['INDEX_MAPPING'])[int(os.environ['JOB_COMPLETION_INDEX'])])")
          else
            # Initial tier: use completion index directly
            INDEX=$JOB_COMPLETION_INDEX
          fi

          echo "Processing wetlands index $INDEX at tier $MEMORY_TIER"

          # Install dependencies
          pip install -q git+https://github.com/boettiger-lab/cng-python

          # Process the wetlands data
          python -u wetlands/nwi.py \
            --i "$INDEX" \
            --zoom 8 \
            --input-url 's3://us-west-2.opendata.source.coop/giswqs/nwi/wetlands/**' \
            --output-url 's3://public-wetlands/nwi/chunks'
        volumeMounts:
        - name: repo
          mountPath: /workspace
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: MEMORY_TIER
          value: '0'
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: GDAL_DATA
          value: /opt/conda/share/gdal
        - name: PROJ_LIB
          value: /opt/conda/share/proj
        resources:
          requests:
            memory: 10Gi
            cpu: '1'
          limits:
            memory: 10Gi
            cpu: '1'
      initContainers:
      - name: git-clone
        image: alpine/git:2.45.2
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -lc
        - git clone --depth 1 "https://github.com/boettiger-lab/datasets.git" /workspace/datasets
        volumeMounts:
        - name: repo
          mountPath: /workspace
        resources:
          requests:
            cpu: '1'
            memory: 1Gi
          limits:
            cpu: '1'
            memory: 1Gi
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
