apiVersion: batch/v1
kind: Job
metadata:
  labels:
    k8s-app: mappinginequality-convert
  name: mappinginequality-convert
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        k8s-app: mappinginequality-convert
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      containers:
      - command:
        - bash
        - -c
        - 'set -e

          chmod +x mappinginequality/convert_gpkg_to_parquet.sh

          ./mappinginequality/convert_gpkg_to_parquet.sh'
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: GDAL_DATA
          value: /opt/conda/share/gdal
        - name: PROJ_LIB
          value: /opt/conda/share/proj
        image: ghcr.io/rocker-org/ml-spatial
        imagePullPolicy: Always
        name: convert-task
        resources:
          limits:
            cpu: '8'
            memory: 16Gi
          requests:
            cpu: '4'
            memory: 8Gi
        volumeMounts:
        - mountPath: /workspace
          name: repo
        workingDir: /workspace/datasets
      initContainers:
      - command:
        - sh
        - -lc
        - git clone --depth 1 "https://github.com/boettiger-lab/datasets.git" /workspace/datasets
        image: alpine/git:2.45.2
        imagePullPolicy: IfNotPresent
        name: git-clone
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        volumeMounts:
        - mountPath: /workspace
          name: repo
      priorityClassName: opportunistic
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: repo
  ttlSecondsAfterFinished: 10800
