apiVersion: batch/v1
kind: Job
metadata:
  name: mappinginequality-convert
  namespace: biodiversity
spec:
  backoffLimitPerIndex: 3
  completions: 1
  parallelism: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      containers:
      - args:
        - "\nimport geopandas as gpd\nimport urllib.request\n\nprint('Downloading\
          \ source data...')\nurllib.request.urlretrieve('https://dsl.richmond.edu/panorama/redlining/static/mappinginequality.gpkg',\
          \ '/tmp/input.gpkg')\n\nprint('Reading and cleaning data...')\ngdf = gpd.read_file('/tmp/input.gpkg')\n\
          \n# Basic cleaning\nfor col in gdf.columns:\n    if col.strip().lower()\
          \ == 'grade' and col != 'grade':\n        gdf = gdf.rename(columns={col:\
          \ 'grade'})\n        gdf['grade'] = gdf['grade'].astype(str).str.strip().replace(['',\
          \ 'nan'], None)\n\nif gdf.geometry.isna().any():\n    gdf = gdf[~gdf.geometry.isna()]\n\
          if not gdf.geometry.is_valid.all():\n    gdf.geometry = gdf.geometry.buffer(0)\n\
          \nprint('Writing to S3...')\ngdf.to_parquet('s3://public-mappinginequality/mappinginequality.parquet')\n\
          print('\u2713 Conversion complete!')\n"
        command:
        - python
        - -c
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        image: ghcr.io/boettiger-lab/cng-datasets:latest
        name: processor
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: '2'
            memory: 8Gi
      priorityClassName: opportunistic
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 10800
