apiVersion: batch/v1
kind: Job
metadata:
  name: mappinginequality-hex
  namespace: biodiversity
spec:
  backoffLimitPerIndex: 3
  completionMode: Indexed
  completions: 50
  parallelism: 20
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      containers:
      - args:
        - '

          set -e

          apt-get update

          pip install geopandas pyarrow duckdb h3 boto3


          cng-datasets vector   --input s3://public-mappinginequality/mappinginequality.parquet   --output
          s3://public-mappinginequality/chunks   --resolution 10   --chunk-size 500   --chunk-id
          $JOB_COMPLETION_INDEX

          '
        command:
        - bash
        - -c
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        image: python:3.12-slim
        name: processor
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
      priorityClassName: opportunistic
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 10800
