apiVersion: batch/v1
kind: Job
metadata:
  name: mappinginequality-pmtiles
  namespace: biodiversity
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      containers:
      - args:
        - "\nset -e\napt-get update && apt-get install -y curl gdal-bin\npip install\
          \ geopandas pyarrow duckdb h3 boto3\n\ncurl -L -o /usr/local/bin/tippecanoe\
          \ https://github.com/felt/tippecanoe/releases/download/2.17.0/tippecanoe-linux-amd64\
          \ && chmod +x /usr/local/bin/tippecanoe\ncurl -L -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc\
          \ && chmod +x /usr/local/bin/mc\n\ncurl -L -o /tmp/input.gpkg https://dsl.richmond.edu/panorama/redlining/static/mappinginequality.gpkg\n\
          ogr2ogr -f GeoJSONSeq /tmp/input.geojsonl /tmp/input.gpkg -progress\ntippecanoe\
          \ -o /tmp/output.pmtiles -l mappinginequality --drop-densest-as-needed --extend-zooms-if-still-dropping\
          \ --force /tmp/input.geojsonl\n\nmc alias set s3 https://${AWS_PUBLIC_ENDPOINT}\
          \ ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}\nmc cp /tmp/output.pmtiles\
          \ s3/public-mappinginequality/mappinginequality.pmtiles\necho \"\u2713 PMTiles\
          \ complete!\"\n"
        command:
        - bash
        - -c
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        image: python:3.12-slim
        name: processor
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: '2'
            memory: 8Gi
      priorityClassName: opportunistic
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 10800
