apiVersion: v1
kind: ServiceAccount
metadata:
  name: mappinginequality-workflow
  namespace: gpn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mappinginequality-workflow
  namespace: gpn
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mappinginequality-workflow
  namespace: gpn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mappinginequality-workflow
subjects:
- kind: ServiceAccount
  name: mappinginequality-workflow
