apiVersion: batch/v1
kind: Job
metadata:
  name: mappinginequality-workflow
  namespace: biodiversity
spec:
  template:
    spec:
      containers:
      - args:
        - "\nset -e\necho \"Starting mappinginequality workflow...\"\n\n# Run convert\
          \ and pmtiles in parallel\nkubectl apply -f /config/convert-job.yaml -n\
          \ biodiversity\nkubectl apply -f /config/pmtiles-job.yaml -n biodiversity\n\
          \nkubectl wait --for=condition=complete --timeout=3600s job/mappinginequality-convert\
          \ -n biodiversity\nkubectl wait --for=condition=complete --timeout=3600s\
          \ job/mappinginequality-pmtiles -n biodiversity\n\n# Run hex tiling\nkubectl\
          \ apply -f /config/hex-job.yaml -n biodiversity\nkubectl wait --for=condition=complete\
          \ --timeout=7200s job/mappinginequality-hex -n biodiversity\n\n# Run repartitioning\n\
          kubectl apply -f /config/repartition-job.yaml -n biodiversity\nkubectl wait\
          \ --for=condition=complete --timeout=3600s job/mappinginequality-repartition\
          \ -n biodiversity\n\necho \"\u2713 Workflow complete!\"\n"
        command:
        - bash
        - -c
        image: bitnami/kubectl:latest
        name: orchestrator
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: config
      restartPolicy: Never
      serviceAccountName: mappinginequality-workflow
      volumes:
      - configMap:
          name: mappinginequality-workflow-config
        name: config
