apiVersion: batch/v1
kind: Job
metadata:
  labels:
    k8s-app: cpad_2025b_holdings-pmtiles
  name: cpad_2025b_holdings-pmtiles
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        k8s-app: cpad_2025b_holdings-pmtiles
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      containers:
      - command:
        - bash
        - -c
        - 'set -e

          # Convert GPKG to GeoJSONSeq for tippecanoe (read directly via vsicurl)

          ogr2ogr -f GeoJSONSeq /tmp/mappinginequality.geojsonl /vsicurl/https://s3-west.nrp-nautilus.io/public-cpad/2025b/CPAD_2025b_Holdings/CPAD_2025b_Holdings.shp
          -progress


          # Generate PMTiles from GeoJSONSeq

          tippecanoe -o /tmp/mappinginequality.pmtiles -l redlining --drop-densest-as-needed
          --extend-zooms-if-still-dropping --force /tmp/mappinginequality.geojsonl


          # Upload to S3

          mc alias set s3 https://$AWS_PUBLIC_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY

          mc cp /tmp/mappinginequality.pmtiles s3/public-cpad/mappinginequality.pmtiles

          rm /tmp/mappinginequality.geojsonl /tmp/mappinginequality.pmtiles

          '
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: GDAL_DATA
          value: /opt/conda/share/gdal
        - name: PROJ_LIB
          value: /opt/conda/share/proj
        - name: TMPDIR
          value: /tmp
        - name: BUCKET
          value: public-cpad
        - name: SOURCE_URL
          value: https://s3-west.nrp-nautilus.io/public-cpad/2025b/CPAD_2025b_Holdings/CPAD_2025b_Holdings.shp
        image: ghcr.io/felt/tippecanoe:latest
        imagePullPolicy: IfNotPresent
        name: pmtiles-task
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
          requests:
            cpu: '4'
            memory: 8Gi
        volumeMounts:
        - mountPath: /workspace
          name: repo
        workingDir: /workspace
      initContainers:
      - command:
        - sh
        - -lc
        - git clone --depth 1 "https://github.com/boettiger-lab/datasets.git" /workspace/repo
        image: alpine/git:2.45.2
        imagePullPolicy: IfNotPresent
        name: git-clone
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        volumeMounts:
        - mountPath: /workspace
          name: repo
      priorityClassName: opportunistic
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: repo
  ttlSecondsAfterFinished: 10800
