apiVersion: batch/v1
kind: Job
metadata:
  name: cpad-2025b-holdings-workflow
  namespace: gpn
spec:
  template:
    spec:
      containers:
      - args:
        - '

          set -e


          echo "Starting cpad-2025b-holdings workflow..."

          echo "Note: Apply jobs from your local machine with:"

          echo "  kubectl apply -f convert-job.yaml"

          echo "  kubectl apply -f pmtiles-job.yaml"

          echo "  kubectl apply -f hex-job.yaml"

          echo "  kubectl apply -f repartition-job.yaml"

          echo ""

          echo "This orchestrator job is deprecated. Use ''kubectl apply'' directly
          from the output directory."

          exit 1

          '
        command:
        - bash
        - -c
        image: bitnami/kubectl:latest
        name: workflow
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      initContainers:
      - args:
        - git clone --depth 1 https://github.com/boettiger-lab/datasets.git /workspace/repo
        command:
        - sh
        - -c
        image: alpine/git:2.45.2
        name: git-clone
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      restartPolicy: OnFailure
      serviceAccountName: cng-datasets-workflow
      volumes:
      - emptyDir: {}
        name: workspace
  ttlSecondsAfterFinished: 10800
