---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-runner
  namespace: biodiversity
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-runner
  namespace: biodiversity
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-runner
  namespace: biodiversity
subjects:
  - kind: ServiceAccount
    name: workflow-runner
    namespace: biodiversity
roleRef:
  kind: Role
  name: workflow-runner
  apiGroup: rbac.authorization.k8s.io
